name: mochi
description: "BloC, clean coding, tdd tutorial"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.7.0
  injectable: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  drift_dev: ^2.16.0

flutter:
  uses-material-design: true

  #
